# Generated by Django 4.0.3 on 2022-06-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('profession', models.CharField(max_length=400)),
                ('contact_number', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('profile_pic', models.ImageField(upload_to='core/')),
            ],
        ),
    ]
