# Generated by Django 4.0.3 on 2022-06-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('breakfast', models.CharField(max_length=1000)),
                ('lunch', models.CharField(max_length=1000)),
                ('dinner', models.CharField(max_length=1000)),
            ],
        ),
    ]
