# Generated by Django 4.0.3 on 2022-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
