# Generated by Django 4.0.3 on 2022-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_age_alter_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emergency_contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='guardian_contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
