# Generated by Django 4.0.3 on 2022-05-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='guardian_contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='work_place',
        ),
        migrations.CreateModel(
            name='HostelCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('duration', models.CharField(max_length=40)),
                ('occupation', models.CharField(max_length=100)),
                ('work_place', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=400)),
                ('caste', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField()),
                ('guardian_name', models.CharField(max_length=400)),
                ('guardian_relation', models.CharField(max_length=400)),
                ('guardian_contact_number', models.PositiveIntegerField()),
                ('emergency_contact_number', models.PositiveIntegerField()),
                ('permanent_address', models.TextField()),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('pincode', models.PositiveIntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
