# Generated by Django 4.0.3 on 2022-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_hostelcustomer_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcustomer',
            name='duration',
            field=models.CharField(choices=[('3 months', '3 Months'), ('6 months', '6 Months'), ('9 months', '9 Months'), ('1 year', '1 Year'), ('more than 1 year', 'More than 1 Year')], max_length=40),
        ),
        migrations.AlterField(
            model_name='hostelcustomer',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('empolyee', 'Empolyee')], max_length=100),
        ),
    ]
