# Generated by Django 4.0.3 on 2022-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_hostelcustomer_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcustomer',
            name='caste',
            field=models.CharField(choices=[('BC-A', 'BC-A'), ('BC-B', 'BC-B'), ('BC-C', 'BC-C'), ('BC-D', 'BC-D'), ('OC', 'OC'), ('SC/ST', 'SC/ST'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
    ]
