# Generated by Django 4.0.3 on 2022-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_hostelcustomer_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelcustomer',
            name='total_fees',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
