# Generated by Django 4.0.3 on 2022-06-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customercomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.hostelcustomer'),
        ),
    ]
