# Generated by Django 4.0.3 on 2022-06-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_designer_resume'),
        ('customer', '0019_rename_customer_customercomplaint_hostel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroom',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.designer'),
        ),
        migrations.AddField(
            model_name='customerroomcustomization',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.designer'),
        ),
        migrations.AlterField(
            model_name='customerroom',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.hostelcustomer'),
        ),
        migrations.AlterField(
            model_name='customerroomcustomization',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.hostelcustomer'),
        ),
    ]
