# Generated by Django 4.0.3 on 2022-06-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_designer_resume'),
        ('customer', '0021_remove_customerroom_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroom',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.designer'),
        ),
    ]
