# Generated by Django 4.0.3 on 2022-06-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_designer_resume'),
        ('customer', '0022_customerroom_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroomcustomization',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.designer'),
        ),
        migrations.AddField(
            model_name='customerroomcustomization',
            name='designer_status',
            field=models.BooleanField(default=False),
        ),
    ]
