# Generated by Django 4.0.3 on 2022-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_customerroomcustomization_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroomcustomization',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
