# Generated by Django 4.0.3 on 2022-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_customerroomcustomization_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroomcustomization',
            name='updated_room',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
