# Generated by Django 4.0.3 on 2022-06-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rules'),
        ('customer', '0026_customerroomcustomization_updated_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcustomer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
