# Generated by Django 4.0.3 on 2022-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_hostelcustomer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='room_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
