# Generated by Django 4.0.3 on 2022-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_customer_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelcustomer',
            name='admin_status',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
