# Generated by Django 4.0.3 on 2022-06-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_hostelcustomer_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcustomer',
            name='admin_status',
            field=models.BooleanField(default=False),
        ),
    ]
