# Generated by Django 4.0.3 on 2022-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_roomcustomization_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcustomization',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
