# Generated by Django 4.0.3 on 2022-06-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_roomcustomization_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcustomization',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.designer'),
        ),
    ]
