# Generated by Django 4.0.3 on 2022-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_alter_roomcustomization_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
