# Generated by Django 4.0.3 on 2022-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_designer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
