# Generated by Django 4.0.3 on 2022-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_designer_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcustomization',
            name='back',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='roomcustomization',
            name='bottom',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
    ]
