# Generated by Django 4.0.3 on 2022-06-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0008_roomcustomization_back_roomcustomization_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcustomization',
            name='theme',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
